-- Community-driven seller trust system for the existing public.users schema.
-- Profiles are created automatically for every local user; no verification badges are used.

alter table public.users
  add column if not exists business_hours text,
  add column if not exists pickup_address text;

create table if not exists public.profiles (
  id bigint primary key references public.users(id) on delete cascade,
  name text not null,
  business_hours text,
  pickup_address text,
  completed_orders_count integer not null default 0 check (completed_orders_count >= 0)
);

create or replace function public.sync_profile_from_user()
returns trigger language plpgsql as $$
begin
  insert into public.profiles (id, name, business_hours, pickup_address)
  values (new.id, new.name, new.business_hours, new.pickup_address)
  on conflict (id) do update set
    name = excluded.name,
    business_hours = excluded.business_hours,
    pickup_address = excluded.pickup_address;
  return new;
end;
$$;

drop trigger if exists users_sync_profile on public.users;
create trigger users_sync_profile after insert or update of name, business_hours, pickup_address on public.users
for each row execute function public.sync_profile_from_user();

insert into public.profiles (id, name, business_hours, pickup_address)
select id, name, business_hours, pickup_address from public.users
on conflict (id) do update set
  name = excluded.name,
  business_hours = excluded.business_hours,
  pickup_address = excluded.pickup_address;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  seller_id bigint not null references public.profiles(id) on delete cascade,
  buyer_id bigint not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) > 0),
  created_at timestamptz not null default now(),
  constraint reviews_seller_buyer_different check (seller_id <> buyer_id)
);

create index if not exists reviews_seller_id_created_at_idx on public.reviews (seller_id, created_at desc);
create index if not exists reviews_buyer_id_idx on public.reviews (buyer_id);

-- Reviews are public to read. Only authenticated Supabase sessions may submit one.
-- The client also checks its buyer_id before inserting; connect that ID to auth users
-- in a future profile-ownership policy if you migrate local users to Supabase Auth.
alter table public.reviews enable row level security;

drop policy if exists reviews_public_read on public.reviews;
create policy reviews_public_read on public.reviews
for select to anon, authenticated using (true);

drop policy if exists reviews_authenticated_insert on public.reviews;
create policy reviews_authenticated_insert on public.reviews
for insert to authenticated with check (auth.uid() is not null);

grant select on public.profiles, public.reviews to anon, authenticated;
grant insert on public.reviews to authenticated;

create or replace view public.seller_ratings as
select seller_id, round(avg(rating)::numeric, 2) as average_rating, count(*)::integer as review_count
from public.reviews
group by seller_id;

grant select on public.seller_ratings to anon, authenticated;

create or replace function public.refresh_completed_orders_count()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    update public.profiles profile
    set completed_orders_count = (
      select count(*)::integer from public.orders order_row
      where order_row.status = 'Completed' and order_row.vendor = profile.name
    )
    where profile.name = old.vendor;
    return old;
  end if;

  update public.profiles profile
  set completed_orders_count = (
    select count(*)::integer from public.orders order_row
    where order_row.status = 'Completed' and order_row.vendor = profile.name
  )
  where profile.name = new.vendor;

  if tg_op = 'UPDATE' and old.vendor <> new.vendor then
    update public.profiles profile
    set completed_orders_count = (
      select count(*)::integer from public.orders order_row
      where order_row.status = 'Completed' and order_row.vendor = profile.name
    )
    where profile.name = old.vendor;
  end if;

  return new;
end;
$$;

drop trigger if exists orders_refresh_completed_orders_count on public.orders;
create trigger orders_refresh_completed_orders_count
after insert or update of status, vendor or delete on public.orders
for each row execute function public.refresh_completed_orders_count();

update public.profiles profile
set completed_orders_count = (
  select count(*)::integer from public.orders order_row
  where order_row.status = 'Completed' and order_row.vendor = profile.name
);
