-- Phase 2: live buyer/seller messages.
-- Link a public.users row to auth.users after Supabase Auth sign-in to enforce
-- per-user RLS ownership (for example, set users.auth_user_id = auth.uid()).

alter table public.users
  add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null references public.users(id) on delete cascade,
  receiver_id bigint not null references public.users(id) on delete cascade,
  -- Uses products.local_id because locally-created product IDs may be text.
  product_id text not null,
  content text not null check (char_length(trim(content)) > 0),
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint messages_sender_receiver_different check (sender_id <> receiver_id)
);

create index if not exists messages_sender_receiver_created_at_idx
  on public.messages (sender_id, receiver_id, created_at);

create index if not exists messages_receiver_is_read_idx
  on public.messages (receiver_id, is_read);

alter table public.messages enable row level security;

drop policy if exists messages_participants_read on public.messages;
create policy messages_participants_read on public.messages
for select to authenticated
using (
  sender_id = (select id from public.users where auth_user_id = auth.uid())
  or receiver_id = (select id from public.users where auth_user_id = auth.uid())
);

drop policy if exists messages_sender_insert on public.messages;
create policy messages_sender_insert on public.messages
for insert to authenticated
with check (
  sender_id = (select id from public.users where auth_user_id = auth.uid())
);

drop policy if exists messages_receiver_update on public.messages;
create policy messages_receiver_update on public.messages
for update to authenticated
using (receiver_id = (select id from public.users where auth_user_id = auth.uid()))
with check (receiver_id = (select id from public.users where auth_user_id = auth.uid()));

grant select, insert, update (is_read) on public.messages to authenticated;

-- Enable this table in Supabase Dashboard > Database > Replication as well,
-- so Postgres INSERT events are delivered to client channels.
