-- Purpose: Keep live chat aligned with the app's existing chat_messages table.
-- This migration intentionally keeps the app on chat_messages.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  local_id text unique,
  conversation_id text not null,
  product_id bigint,
  product_local_id text,
  product_name text not null,
  buyer_id bigint,
  buyer_local_id text,
  buyer_name text not null,
  seller_name text not null,
  sender_role text not null check (sender_role in ('buyer', 'seller')),
  message text not null,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.chat_messages
  add column if not exists delivered_at timestamptz,
  add column if not exists read_at timestamptz;

create index if not exists chat_messages_conversation_id_idx
  on public.chat_messages (conversation_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;
