-- Purpose: Supabase/Postgres schema for UPNM Campus Marketplace online database.
-- Paste this into Supabase SQL Editor when you are ready to create the live tables.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  local_id text unique,
  name text not null,
  email text not null unique,
  phone text default '',
  password text not null,
  role text not null check (role in ('buyer', 'seller', 'admin')),
  avatar text default '',
  payment_qr text default '',
  recovery_code text default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  local_id text unique,
  seller_id bigint,
  seller_local_id text,
  seller text default '',
  vendor text not null,
  category text not null,
  name text not null,
  image text not null,
  price numeric(10, 2) not null default 0,
  stock integer,
  desc1 text not null,
  variations jsonb not null default '[]'::jsonb,
  addons jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  local_id text unique,
  buyer_id bigint,
  buyer_local_id text,
  product_id bigint,
  product_local_id text,
  product_name text not null,
  vendor text not null,
  image text default '',
  quantity integer not null default 1,
  total numeric(10, 2) not null default 0,
  selected_variation text default '',
  selected_addons jsonb not null default '[]'::jsonb,
  receipt text default '',
  receipt_file_name text default '',
  status text not null default 'In Progress',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  local_id text unique,
  conversation_id text not null,
  product_id bigint,
  product_local_id text,
  product_name text not null,
  buyer_id bigint,
  buyer_local_id text,
  buyer_name text not null,
  seller_name text not null,
  sender_role text not null check (sender_role in ('buyer', 'seller')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_conversation_id_idx
  on public.chat_messages (conversation_id);

create index if not exists products_seller_id_idx
  on public.products (seller_id);

create index if not exists orders_buyer_id_idx
  on public.orders (buyer_id);

insert into public.users (name, email, phone, password, role, recovery_code, active)
values
  ('Aiman Buyer', 'buyer@upnm.test', '', '123456', 'buyer', 'BUYER-2026', true),
  ('Campus Kitchen', 'seller@upnm.test', '', '123456', 'seller', 'SELLER-2026', true),
  ('Admin User', 'admin@upnm.test', '', '123456', 'admin', 'ADMIN-2026', true)
on conflict (email) do nothing;
  